[
  {
    "Id": "290683",
    "ThreadId": "85334",
    "Html": "<p>I have an exception thrown from some code and it's not handled which means it eventually ends up in the UnhandledException hander. &nbsp;Problem is that whenever I try to show something to the user it seems to just re-throw the same error. &nbsp;For example, a MessageBox.Show(ex.ToString()) as per the StockTrader sample app just throws again:</p>\r\n<p><em>Exception has been thrown by the target of an invocation.</em></p>\r\n<p>If I try and fire up a window it does the same thing. &nbsp;The error message is of no help I don't think.</p>\r\n<p>Any ideas?</p>",
    "PostedDate": "2010-02-14T16:02:14.833-08:00",
    "UserRole": null,
    "MarkedAsAnswerDate": null
  }
]